config/routes.rb
Itag::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :edit, :update, :index] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resource :session, :only => [:create, :destroy, :new]

  resources :restaurants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  get 'search' => "restaurants#search"

  resources :cities, :only => [:show, :index] do
    resources :restaurants, :only => [:index, :new, :create]
  end

  resources :reviews, :only => [:show, :edit, :update, :destroy] do
    resources :vote_tags, :only => [:create, :destroy]
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  root :to => "cities#index"

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :require_signed_in!

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
    if @restaurant.open == false
      render json: "That restaurant is closed!"
    end
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = current_user.reviews.new(params[:review])
    @review.restaurant_id = @restaurant.id
    @review.save

    push_review(@review)

    if request.xhr?
      headers["Content-Type"] = 'text/html; charset=utf-8'
      render partial: "jsform", locals: {review: @review}
    else
      redirect_to restaurant_url(@review.restaurant)
    end

    # else
    #   render json: @review.errors.full_messages
    # end
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = current_user.reviews.find(params[:id])
  end

  def update
    @review = current_user.reviews.find(params[:id])

    if @review.update_attributes(params[:review])
      redirect_to user_url(@review.user)
    else
      render json: @review.errors.full_messages
    end
  end

  def index
    @reviews = Review.all
  end

  def destroy
    @review = Review.find(params[:id])

    if (current_user.admin == true && !current_user.reviews.include?(@review))
      @review.destroy
      redirect_to restaurant_url(@review.restaurant)
    else
      @review.destroy
      redirect_to user_url(@review.user)
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<% action = (review.persisted? ? review_url(review) : restaurant_reviews_url(restaurant)) %>
<% method = (review.persisted? ? "put" : "post") %>
<% message = (review.persisted? ? "Update Review!" : "Create Review!") %>

<form class="form" action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

 <h1><%= message %></h1>

 <div class="input">
  <label for="review_rating">Rating</label>
  <select id="review_rating" name="review[rating]">
    <option value="1" <%= "selected" if @review.rating == 1 %>>1</option>
    <option value="2" <%= "selected" if @review.rating == 2 %>>2</option>
    <option value="3"<%= "selected" if @review.rating == 3 %>>3</option>
    <option value="4" <%= "selected" if @review.rating == 4 %>>4</option>
    <option value="5" <%= "selected" if @review.rating == 5 %>>5</option>
  </select>
 </div>

 <div class="input">
  <label for="review_email">Review Title</label>
  <input
     id="review_title"
     name="review[title]"
     type="text"
     value="<%= @review.title %>">
  <br>
</div>

<div class="input">
  <label for="review_body">Review Body</label><br>
<textarea rows="4"
          cols="50"
          id="review_body"
          name="review[body]"><%= @review.body %></textarea>
</div>

 <div class="submit">
  <input type="submit" value="<%= message %>">
 </div>
</form>

app/views/reviews/_index.html.erb
<% restaurant.reviews.sort_by{ |rev| rev.created_at }.reverse!.each do |review| %>

<div class="review">

  <strong>"<%= review.title %>"</strong> by <%= link_to review.user.username, user_url(review.user) %> <div class="review-date"><% if review.created_at > Time.now.beginning_of_day %>
        <%="(written #{time_ago_in_words(review.created_at)} ago)"%>
    <% else %>
        <%= review.created_at.strftime("(%m/%d/%Y)") %>
    <% end %></div>

  <br>
  Rating: <%= review.rating %>
  <br>
  <div class="review-body">
  <%= review.body %>
  </div>

  <% unless current_user == review.user %>
    <% if current_user.voted_reviews.include?(review) %>
      <%= button_to "Uncool...", review_vote_tag_url(review), method: :delete, form_class: "cool-button" %>
    <% else %>
      <%= button_to "Cool review!", review_vote_tags_url(review), method: :post, form_class: "cool-button" %>
    <% end %>
  <% else %>
  cool votes
  <% end %>

    <% if review.vote_tags.empty? %>
    <strong class="badge">0</strong>
    <% else %>
    <strong class="badge"><%= review.vote_tags.count %></strong>
    <% end %>

    <br><br>

    <% if current_user && current_user.admin == true %>
      <%= button_to "Delete Review", review_url(review), method: :delete, form_class: "delete-review" %>
    <% end %>

</div>
<% end %>

app/views/reviews/_jsform.html.erb
<div class="review">

  <strong>"<%= review.title %>"</strong> by <%= link_to review.user.username, user_url(review.user) %>
  <div class="review-date"> <%="(written #{time_ago_in_words(review.created_at)} ago)"%></div>

  <br>
  Rating: <%= review.rating %>
  <br>
  <div class="review-body">
  <%= review.body %>
  </div>

</div>

app/views/reviews/_pusherform.erb
<div class="review" data-id="<%= review.restaurant.city.id %>">

  <h3><%=link_to review.restaurant.name, restaurant_url(review.restaurant) %></h3>
  <strong>"<%= review.title %>"</strong> by <%= link_to review.user.username, user_url(review.user) %>
  <div class="review-date"> <%="(written #{time_ago_in_words(review.created_at)} ago)"%></div>

  <br>
  Rating: <%= review.rating %>
  <br>
  <div class="review-body">
  <%= review.body %>
  </div>

</div>

app/views/reviews/_user.html.erb
<% user.reviews.sort_by{ |rev| rev.created_at }.reverse!.each do |review| %>

<div class="prof-review group">

  <h4><%= link_to review.restaurant.name, restaurant_url(review.restaurant) %></h4>
    <% if current_user == @user %>
      (<%= link_to "Edit Review", edit_review_url(review) %>)
    <% end %>
  <br>
  Rating: <%= review.rating %>
  <br>
  <strong>"<%= review.title %>"</strong>
  <br>

  <div class="review-body">
  <%= review.body %>

  <% if review.created_at > Time.now.beginning_of_day %>
      <br><%="Written #{time_ago_in_words(review.created_at)} ago"%>
  <% else %>
      <br>Written on <%= review.created_at.strftime("%m/%d/%Y") %>
  <% end %>
  </div>

</div>
<br>

<% end %>

app/views/reviews/edit.html.erb
<%= render "form", :review => @review %>

<br><br>

<div class="delete-button">
  <%= button_to "Delete Review", review_url(@review), method: :delete, form_class: "delete grad_button" %>
</div>

<div class="back-button">
  <%= link_to "Back", user_url(current_user), method: :get, class: "back grad_button" %>
</div>

app/views/reviews/new.html.erb
<%= render "form", :restaurant => @restaurant, :review => @review %>

<div class="back-button">
  <%= link_to "Back", restaurant_url(@restaurant), class: "back grad_button" %>
</div>

app/views/reviews/show.html.erb
<h1><%= @review.title %></h1>

<% if current_user == @user %>
  <%= link_to "Edit Review", edit_user_review(@review) %>
<% end %>