config/routes.rb
Itag::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :edit, :update, :index] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resource :session, :only => [:create, :destroy, :new]

  resources :restaurants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  get 'search' => "restaurants#search"

  resources :cities, :only => [:show, :index] do
    resources :restaurants, :only => [:index, :new, :create]
  end

  resources :reviews, :only => [:show, :edit, :update, :destroy] do
    resources :vote_tags, :only => [:create, :destroy]
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  root :to => "cities#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :tags

  has_many :restaurants,
  through: :tags,
  source: :restaurant

  include PgSearch
    multisearchable :against => [:name]

end

app/models/city.rb
class City < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  attr_accessible :name, :state_id

  validates :name, :state_id, presence: true
  validates :name, uniqueness: { scope: :state_id }

  belongs_to :state

  has_many :restaurants
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :user_id, :restaurant_id

  validates :user_id, :restaurant_id, presence: true
  validates :user_id, uniqueness: { scope: :restaurant_id, message: "You already favorited that place!" }

  belongs_to :user

  belongs_to :restaurant

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  attr_accessible :follower_id, :followed_id

  validates :follower_id, :followed_id, presence: true
  validates :follower_id, uniqueness: { scope: :followed_id, message: "You already followed this reviewer!" }

  belongs_to :follower,
  class_name: "User",
  foreign_key: :follower_id,
  primary_key: :id

  belongs_to :followed,
  class_name: "User",
  foreign_key: :followed_id,
  primary_key: :id

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  attr_accessible :name, :website, :price, :phone, :street, :city_id, :zip, :open, :category_ids, :photo

  validates :name, :street, :city_id, presence: true

  validates :name, uniqueness: {:scope => :street, :message => "That listing already exists!"}

  has_attached_file :photo, :styles => {
    :big => "250x250>",
    :medium => "100x100#",
    :small => "60x60#"
  }

  paginates_per 5

  include PgSearch
    multisearchable :against => [:name]

  has_many :tags

  has_many :categories,
  through: :tags,
  source: :category

  has_many :reviews

  has_many :reviewers,
  through: :reviews,
  source: :user

  belongs_to :city

  has_one :state,
  through: :city

  has_many :favorites

  has_many :users_who_favorited,
  through: :favorites,
  source: :user

  def average_rating
    total = 0
    count = self.reviews.count

    if count == 0
      return 0
    else
      self.reviews.each do |review|
        total += review.rating
      end

      return (total.to_f / count).round(1)
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :title, :body, :rating, :user_id, :restaurant_id

  validates :title, :body, :rating, :user_id, :restaurant_id, presence: true
  validates :restaurant_id, uniqueness: { :scope => :user_id, :message => "You already wrote a review for this place!" }
  validates :title, length: { minimum: 3, message: "title too short!" }
  validates :body, length: { minimum: 6, message: "body too short!" }

  belongs_to :restaurant

  belongs_to :user

  has_many :vote_tags

  has_many :users_who_voted,
  through: :vote_tags,
  source: :user

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true
  validate :name, uniqueness: true

  has_many :cities
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :restaurant_id, :category_id

  validates :restaurant_id, :category_id, presence: true
  validates :restaurant_id, uniqueness: { scope: :category_id }

  belongs_to :restaurant

  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, :use => :slugged

  attr_accessible :username, :password, :email, :biography, :age, :gender, :location, :admin, :session_token, :photo, :uid, :provider, :image, :auth_token, :activated
  attr_reader :password

  before_validation :ensure_session_token
  before_validation(:ensure_auth_token, on: :create)

  validates :username, :email, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, :allow_nil => true }
  validates :password_digest, presence: true
  validates :username, :email, uniqueness: true

  has_attached_file :photo, :styles => {
    :big => "100x100#",
    :small => "60x60#"
  }

  has_many :reviews,
  dependent: :destroy

  has_many :rated_restaurants,
  through: :reviews,
  source: :restaurant

  has_many :favorites,
  dependent: :destroy

  has_many :favorite_places,
  through: :favorites,
  source: :restaurant

  has_many :follows,
  class_name: "Follow",
  foreign_key: :followed_id,
  primary_key: :id,
  dependent: :destroy

  has_many :followed,
  class_name: "Follow",
  foreign_key: :follower_id,
  primary_key: :id,
  dependent: :destroy

  has_many :followers,
  through: :follows,
  source: :follower

  has_many :followed_users,
  through: :followed,
  source: :followed

  has_many :vote_tags,
  dependent: :destroy

  has_many :voted_reviews,
  through: :vote_tags,
  source: :review

  def self.find_uid_or_create(auth)

    user = User.find_by_uid(auth[:uid])

    unless user
      if auth[:provider] == 'facebook'
        user = User.create!(
                 uid: auth[:uid],
                 provider: auth[:provider],
                 username: (auth[:info][:nickname] || auth[:info][:first_name]+rand(1..1000).to_s),
                 email: auth[:info][:email],
                 image: auth[:info][:image] + "?type=large",
                 password: SecureRandom::urlsafe_base64(16)
               )
      elsif auth[:provider] == 'twitter'
        user = User.create!(
                 uid: auth[:uid],
                 provider: auth[:provider],
                 username: auth[:info][:nickname],
                 email: "fillmein@right.meow",
                 image: auth[:info][:image].gsub("_normal", ""),
                 password: SecureRandom::urlsafe_base64(16)
               )
      else
        #asdf
      end
    end

    return user
  end


  def self.find_by_credentials(username, password)
    user = (User.find_by_username(username) || User.find_by_email(username))
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def activate!
    self.activated = true
    self.save
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def ensure_auth_token
    self.auth_token ||= self.class.generate_session_token
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :vote_tags

  has_many :users,
  through: :vote_tags,
  source: :user

end

app/models/vote_tag.rb
class VoteTag < ActiveRecord::Base
  attr_accessible :vote_id, :review_id, :user_id

  validates :vote_id, :review_id, :user_id, presence: true

  validates :user_id, uniqueness: { scope: :review_id, message: "You already upvoted this review!" }

  belongs_to :vote

  belongs_to :review

  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vote_tags_helper.rb
module VoteTagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="icon" type="image/png" href="http://i.imgur.com/QwzZ4bE.png">
<html>
<head>
  <title>Is that any good?</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav class="top-nav group">
    <div class="container group">

      <div class="info">
        <ul>
          <strong>
          <% if signed_in? %>
            <li>User:
              <%= link_to current_user.username, user_url(current_user) %>
              <%= "(admin)" if current_user.admin == true %>
            </li>
            <li><%= link_to "Sign Out", session_url, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_session_url %></li>
            <li><%= link_to "Sign up", new_user_url %></li>
          <% end %>
          </strong>
        </ul>
      </div>

      <div class="logo">
        <a href="/">
          <img src="http://i.imgur.com/juvmlpu.png">
        </a>
      </div>

      <div class="search group">
        <form class="group" action="<%= search_url %>" method="get">
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

        <div class="search-box group">
          <label>Find</label>
          <input type="text" name="query" value="">
        </div>

        <div class="search-box group">
          <label>In</label>
          <select name="city_id" class="search-select">
          <% City.all.each do |city| %>
            <option value="<%= city.id %>">
              <%= city.name %>, <%= city.state.name %>
            </option>
          <% end %>
          </select>
        </div>

        <div class="search-submit group">
          <input id="find" type="submit" value="">
        </div>
        </form>

        <ul class="mini-nav group">
          <%= link_to "<li>Home</li>".html_safe, "/" %>
          <% if signed_in? %>
            <%= link_to "<li>My Profile</li>".html_safe, user_url(current_user)%>
          <% else %>
            <%= link_to "<li>My Profile</li>".html_safe, new_session_url %>
          <% end %>
            <%= link_to "<li>Find Friends</li>".html_safe, users_url %>
        </ul>
      </div>

    </div>
  </nav>
</header>

<main>
  <div class="main group">

    <%= yield %>

  </div>
</main>


<footer class="group">
  <div class="footer group">

    Copyright © 2014 :D

  </div>
</footer>

</body>
</html>